In [ ]:
!apt-get install -y r-base
!pip install rpy2

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
r-base is already the newest version (4.6.0-4.2204.0).
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
Requirement already satisfied: rpy2 in /usr/local/lib/python3.12/dist-packages (3.5.17)
Requirement already satisfied: cffi>=1.15.1 in /usr/local/lib/python3.12/dist-packages (from rpy2) (2.0.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from rpy2) (3.1.6)
Requirement already satisfied: tzlocal in /usr/local/lib/python3.12/dist-packages (from rpy2) (5.3.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.15.1->rpy2) (3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->rpy2) (3.0.3)

In [ ]:
%load_ext rpy2.ipython

In [ ]:
%%R
install.packages("xts")

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
also installing the dependency ‘zoo’

trying URL 'https://cran.rstudio.com/src/contrib/zoo_1.8-15.tar.gz'
trying URL 'https://cran.rstudio.com/src/contrib/xts_0.14.2.tar.gz'

The downloaded source packages are in
	‘/tmp/RtmpITgvey/downloaded_packages’

In [ ]:
%%R
library(xts)

Loading required package: zoo

Attaching package: ‘zoo’

The following objects are masked from ‘package:base’:

    as.Date, as.Date.numeric

In [ ]:
%%R
install.packages(
    "CASdatasets",
    repos = "https://cas.uqam.ca/pub/",
    type = "source"
)

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
trying URL 'https://cas.uqam.ca/pub/src/contrib/CASdatasets_1.2-0.tar.gz'
Content type 'application/x-gzip' length 247610423 bytes (236.1 MB)
==================================================
downloaded 236.1 MB


The downloaded source packages are in
	‘/tmp/RtmpITgvey/downloaded_packages’

In [ ]:

%%R
library(CASdatasets)

data(austri1autoBI7895)

names(austri1autoBI7895)

[1] "paid"  "incur" "nb"    "expo"  "infl"

Loading required package: survival

In [ ]:
%%R
write.csv(
    austri1autoBI7895$paid,
    "/content/paid_triangle.csv"
)

write.csv(
    austri1autoBI7895$incur,
    "/content/incurred_triangle.csv"
)

write.csv(
    austri1autoBI7895$nb,
    "/content/claim_count_triangle.csv"
)

In [ ]:
import pandas as pd

paid = pd.read_csv("/content/paid_triangle.csv", index_col=0)
incurred = pd.read_csv("/content/incurred_triangle.csv", index_col=0)
claim_count = pd.read_csv("/content/claim_count_triangle.csv", index_col=0)

In [ ]:
paid.columns = paid.columns.astype(int)
paid_cum = paid.cumsum(axis=1)
paid_cum.columns = paid_cum.columns.astype(int)

In [ ]:
print(paid.shape)
paid.head()

(18, 18)

,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
1978,1043,2907.0,3511.0,4314.0,3832.0,2032.0,1865.0,2684.0,1431.0,230.0,145.0,528.0,250.0,0.0,529.0,84.0,71.0,13.0
1979,1290,3874.0,3533.0,3942.0,1496.0,2051.0,850.0,1126.0,738.0,113.0,27.0,208.0,215.0,367.0,7.0,0.0,0.0,NaN
1980,1752,4237.0,4392.0,5390.0,4915.0,3503.0,2523.0,1001.0,1171.0,477.0,942.0,506.0,383.0,424.0,347.0,30.0,NaN,NaN
1981,2243,4062.0,6766.0,6783.0,4697.0,4046.0,2854.0,2190.0,1353.0,1435.0,2269.0,233.0,35.0,42.0,110.0,NaN,NaN,NaN
1982,1152,5201.0,5872.0,8359.0,5748.0,3749.0,1760.0,1218.0,1728.0,2827.0,803.0,264.0,402.0,346.0,NaN,NaN,NaN,NaN

In [ ]:
print(incurred.shape)
incurred.head()

(18, 18)

,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
1978,9268,8995.0,1919.0,2201.0,399.0,3566.0,-176.0,12.0,-729.0,285.0,-29.0,-259.0,8.0,-38.0,-36.0,134.0,126.0,-177.0
1979,9848,6275.0,976.0,1445.0,1990.0,1020.0,1665.0,-838.0,-797.0,-176.0,-551.0,306.0,-681.0,-511.0,-13.0,-11.0,44.0,NaN
1980,13990,8494.0,2466.0,8305.0,40.0,1013.0,-286.0,1.0,-181.0,91.0,-363.0,-1689.0,322.0,142.0,-95.0,-82.0,NaN,NaN
1981,16550,11506.0,11939.0,2464.0,338.0,-42.0,-320.0,-133.0,-207.0,-489.0,-1166.0,-8.0,-106.0,11.0,-241.0,NaN,NaN,NaN
1982,11100,20520.0,9232.0,-2021.0,685.0,354.0,488.0,-3.0,-239.0,-230.0,12.0,249.0,-320.0,373.0,NaN,NaN,NaN,NaN

In [ ]:
print(claim_count.shape)
claim_count.head()

(18, 18)

,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
1978,368,191.0,28.0,8.0,6.0,5.0,3.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1979,393,151.0,25.0,6.0,4.0,5.0,4.0,1.0,2.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
1980,517,185.0,29.0,17.0,11.0,10.0,8.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN
1981,578,254.0,49.0,22.0,17.0,6.0,3.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
1982,622,206.0,39.0,16.0,3.0,7.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN

**The dataset documentation states that we have a incremental traingle. So we have to convert it into Cumulative Triangle so that we can work with chainladder method.**

In [ ]:
paid_cum = paid.cumsum(axis=1)
incurred_cum = incurred.cumsum(axis=1)
nb_cum = claim_count.cumsum(axis=1)

In [ ]:
paid_cum.head()

,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
1978,1043.0,3950.0,7461.0,11775.0,15607.0,17639.0,19504.0,22188.0,23619.0,23849.0,23994.0,24522.0,24772.0,24772.0,25301.0,25385.0,25456.0,25469.0
1979,1290.0,5164.0,8697.0,12639.0,14135.0,16186.0,17036.0,18162.0,18900.0,19013.0,19040.0,19248.0,19463.0,19830.0,19837.0,19837.0,19837.0,NaN
1980,1752.0,5989.0,10381.0,15771.0,20686.0,24189.0,26712.0,27713.0,28884.0,29361.0,30303.0,30809.0,31192.0,31616.0,31963.0,31993.0,NaN,NaN
1981,2243.0,6305.0,13071.0,19854.0,24551.0,28597.0,31451.0,33641.0,34994.0,36429.0,38698.0,38931.0,38966.0,39008.0,39118.0,NaN,NaN,NaN
1982,1152.0,6353.0,12225.0,20584.0,26332.0,30081.0,31841.0,33059.0,34787.0,37614.0,38417.0,38681.0,39083.0,39429.0,NaN,NaN,NaN,NaN

In [ ]:
incurred_cum.head()

,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
1978,9268.0,18263.0,20182.0,22383.0,22782.0,26348.0,26172.0,26184.0,25455.0,25740.0,25711.0,25452.0,25460.0,25422.0,25386.0,25520.0,25646.0,25469.0
1979,9848.0,16123.0,17099.0,18544.0,20534.0,21554.0,23219.0,22381.0,21584.0,21408.0,20857.0,21163.0,20482.0,19971.0,19958.0,19947.0,19991.0,NaN
1980,13990.0,22484.0,24950.0,33255.0,33295.0,34308.0,34022.0,34023.0,33842.0,33933.0,33570.0,31881.0,32203.0,32345.0,32250.0,32168.0,NaN,NaN
1981,16550.0,28056.0,39995.0,42459.0,42797.0,42755.0,42435.0,42302.0,42095.0,41606.0,40440.0,40432.0,40326.0,40337.0,40096.0,NaN,NaN,NaN
1982,11100.0,31620.0,40852.0,38831.0,39516.0,39870.0,40358.0,40355.0,40116.0,39886.0,39898.0,40147.0,39827.0,40200.0,NaN,NaN,NaN,NaN

# Functions

In [ ]:
def calculate_age_to_age_factors(cumulative_triangle):
    """
    Calculate individual age-to-age factors for every accident year.

    Parameters
    ----------
    cumulative_triangle : pd.DataFrame
        Cumulative loss triangle

    Returns
    -------
    pd.DataFrame
        Age-to-age factor matrix
    """

    factors = pd.DataFrame(index=cumulative_triangle.index)

    for col in range(cumulative_triangle.shape[1] - 1):

        current = cumulative_triangle.iloc[:, col]
        nxt = cumulative_triangle.iloc[:, col + 1]

        factors[f"{col+1}->{col+2}"] = nxt / current

    return factors

In [ ]:
def calculate_ldfs(cumulative_triangle):
    """
    Calculate volume-weighted Chain Ladder LDFs.

    Parameters
    ----------
    cumulative_triangle : pd.DataFrame

    Returns
    -------
    pd.DataFrame
    """

    results = []

    for col in range(cumulative_triangle.shape[1] - 1):

        current = cumulative_triangle.iloc[:, col]
        nxt = cumulative_triangle.iloc[:, col + 1]

        valid = current.notna() & nxt.notna()

        ldf = nxt[valid].sum() / current[valid].sum()

        results.append({
            "Development": f"{col+1} -> {col+2}",
            "LDF": ldf
        })

    return pd.DataFrame(results)

In [ ]:
def calculate_cdfs(ldf_df):
    """
    Calculate cumulative development factors.
    """

    ldfs = ldf_df["LDF"].values

    cdfs = []

    running_product = 1

    for ldf in reversed(ldfs):
        running_product *= ldf
        cdfs.append(running_product)

    cdfs.reverse()

    result = ldf_df.copy()
    result["CDF"] = cdfs

    return result

In [ ]:
def get_latest_diagonal(cumulative_triangle):

    results = []

    for ay in cumulative_triangle.index:

        row = cumulative_triangle.loc[ay]

        latest_col = row.last_valid_index()

        latest_value = row[latest_col]

        results.append({
            "AccidentYear": ay,
            "DevelopmentAge": int(latest_col),
            "LatestValue": latest_value
        })

    return pd.DataFrame(results)

In [ ]:
def estimate_ultimate_losses(latest_diag, cdf_lookup):

    results = []

    for _, row in latest_diag.iterrows():

        age = int(row["DevelopmentAge"])

        latest = float(row["LatestValue"])

        cdf = cdf_lookup.get(age)

        if cdf is None:
            raise ValueError(f"No CDF found for development age {age}")

        ultimate = latest * cdf
        reserve = ultimate - latest

        results.append({
            "AccidentYear": row["AccidentYear"],
            "DevelopmentAge": age,
            "LatestValue": latest,
            "CDF": cdf,
            "Ultimate": ultimate,
            "Reserve": reserve
        })

    return pd.DataFrame(results)

In [ ]:
def build_cdf_lookup(cdf_table):

    lookup = {
        i: cdf
        for i, cdf in enumerate(
            cdf_table["CDF"],
            start=1
        )
    }

    lookup[len(cdf_table) + 1] = 1.0

    return lookup

# Paid triangle

In [ ]:
paid_link_ratios = calculate_age_to_age_factors(paid_cum)

paid_link_ratios.head()

,1->2,2->3,3->4,4->5,5->6,6->7,7->8,8->9,9->10,10->11,11->12,12->13,13->14,14->15,15->16,16->17,17->18
1978,3.787152,1.888861,1.578207,1.325435,1.130198,1.105732,1.137613,1.064494,1.009738,1.006080,1.022006,1.010195,1.000000,1.021355,1.003320,1.002797,1.000511
1979,4.003101,1.684160,1.453260,1.118364,1.145101,1.052515,1.066095,1.040634,1.005979,1.001420,1.010924,1.011170,1.018856,1.000353,1.000000,1.000000,NaN
1980,3.418379,1.733344,1.519218,1.311648,1.169342,1.104304,1.037474,1.042255,1.016514,1.032083,1.016698,1.012431,1.013593,1.010975,1.000939,NaN,NaN
1981,2.810967,2.073117,1.518935,1.236577,1.164800,1.099801,1.069632,1.040219,1.041007,1.062286,1.006021,1.000899,1.001078,1.002820,NaN,NaN,NaN
1982,5.514757,1.924288,1.683763,1.279246,1.142374,1.058509,1.038253,1.052270,1.081266,1.021348,1.006872,1.010393,1.008853,NaN,NaN,NaN,NaN

In [ ]:
paid_selected_ldfs = calculate_ldfs(paid_cum)
paid_selected_ldfs

   Development       LDF
0       1 -> 2  3.232377
1       2 -> 3  1.891960
2       3 -> 4  1.628007
3       4 -> 5  1.358567
4       5 -> 6  1.229384
5       6 -> 7  1.163152
6       7 -> 8  1.091642
7       8 -> 9  1.062823
8      9 -> 10  1.036874
9     10 -> 11  1.028032
10    11 -> 12  1.014036
11    12 -> 13  1.008709
12    13 -> 14  1.007682
13    14 -> 15  1.008618
14    15 -> 16  1.001479
15    16 -> 17  1.001570
16    17 -> 18  1.000511

In [ ]:
paid_cdf_table = calculate_cdfs(paid_selected_ldfs)

paid_cdf_table

   Development       LDF        CDF
0       1 -> 2  3.232377  24.956464
1       2 -> 3  1.891960   7.720777
2       3 -> 4  1.628007   4.080835
3       4 -> 5  1.358567   2.506646
4       5 -> 6  1.229384   1.845066
5       6 -> 7  1.163152   1.500806
6       7 -> 8  1.091642   1.290292
7       8 -> 9  1.062823   1.181973
8      9 -> 10  1.036874   1.112108
9     10 -> 11  1.028032   1.072558
10    11 -> 12  1.014036   1.043312
11    12 -> 13  1.008709   1.028871
12    13 -> 14  1.007682   1.019988
13    14 -> 15  1.008618   1.012212
14    15 -> 16  1.001479   1.003563
15    16 -> 17  1.001570   1.002082
16    17 -> 18  1.000511   1.000511

In [ ]:
paid_cdf_lookup = {}

for i, cdf in enumerate(
    paid_cdf_table["CDF"],
    start=1
):
    paid_cdf_lookup[i] = cdf

paid_cdf_lookup[len(paid_cdf_table) + 1] = 1.0

In [ ]:
paid_latest_diag = get_latest_diagonal(paid_cum)

paid_latest_diag.head()

   AccidentYear  DevelopmentAge  LatestValue
0          1978              18      25469.0
1          1979              17      19837.0
2          1980              16      31993.0
3          1981              15      39118.0
4          1982              14      39429.0

In [ ]:
ultimate_table_paid = estimate_ultimate_losses(
    paid_latest_diag,
    paid_cdf_lookup
)
ultimate_table_paid["ReservePct"] = (
    ultimate_table_paid["Reserve"] /
    ultimate_table_paid["Ultimate"]
)
ultimate_table_paid

,AccidentYear,DevelopmentAge,LatestValue,CDF,Ultimate,Reserve,ReservePct
0,1978.0,18,25469.0,1.000000,25469.000000,0.000000,0.000000
1,1979.0,17,19837.0,1.000511,19847.130460,10.130460,0.000510
2,1980.0,16,31993.0,1.002082,32059.594043,66.594043,0.002077
3,1981.0,15,39118.0,1.003563,39257.384355,139.384355,0.003551
4,1982.0,14,39429.0,1.012212,39910.496322,481.496322,0.012064
5,1983.0,13,36354.0,1.019988,37080.626435,726.626435,0.019596
6,1984.0,12,48561.0,1.028871,49962.996697,1401.996697,0.028061
7,1985.0,11,39959.0,1.043312,41689.697210,1730.697210,0.041514
8,1986.0,10,41255.0,1.072558,44248.394839,2993.394839,0.067650
9,1987.0,9,40206.0,1.112108,44713.405456,4507.405456,0.100807
10,1988.0,8,33364.0,1.181973,39435.354613,6071.354613,0.153957
11,1989.0,7,37319.0,1.290292,48152.408751,10833.408751,0.224982
12,1990.0,6,35745.0,1.500806,53646.306714,17901.306714,0.333691
13,1991.0,5,29449.0,1.845066,54335.359373,24886.359373,0.458014
14,1992.0,4,28265.0,2.506646,70850.335910,42585.335910,0.601060
15,1993.0,3,15165.0,4.080835,61885.866915,46720.866915,0.754952
16,1994.0,2,7962.0,7.720777,61472.824352,53510.824352,0.870479
17,1995.0,1,2725.0,24.956464,68006.363826,65281.363826,0.959930

# Incurred Claims Triangle

In [ ]:
incurred_link_ratios = calculate_age_to_age_factors(incurred_cum)
incurred_link_ratios.head()

,1->2,2->3,3->4,4->5,5->6,6->7,7->8,8->9,9->10,10->11,11->12,12->13,13->14,14->15,15->16,16->17,17->18
1978,1.970544,1.105076,1.109058,1.017826,1.156527,0.993320,1.000459,0.972159,1.011196,0.998873,0.989926,1.000314,0.998507,0.998584,1.005278,1.004937,0.993098
1979,1.637185,1.060535,1.084508,1.107312,1.049674,1.077248,0.963909,0.964389,0.991846,0.974262,1.014671,0.967821,0.975051,0.999349,0.999449,1.002206,NaN
1980,1.607148,1.109678,1.332866,1.001203,1.030425,0.991664,1.000029,0.994680,1.002689,0.989302,0.949687,1.010100,1.004410,0.997063,0.997457,NaN,NaN
1981,1.695227,1.425542,1.061608,1.007961,0.999019,0.992515,0.996866,0.995107,0.988383,0.971975,0.999802,0.997378,1.000273,0.994025,NaN,NaN,NaN
1982,2.848649,1.291967,0.950529,1.017641,1.008958,1.012240,0.999926,0.994078,0.994267,1.000301,1.006241,0.992029,1.009366,NaN,NaN,NaN,NaN

In [ ]:
incurred_selected_ldfs = calculate_ldfs(incurred_cum)
incurred_selected_ldfs

   Development       LDF
0       1 -> 2  1.998324
1       2 -> 3  1.290667
2       3 -> 4  1.123524
3       4 -> 5  1.072546
4       5 -> 6  1.046308
5       6 -> 7  1.018509
6       7 -> 8  1.000398
7       8 -> 9  0.989474
8      9 -> 10  0.995176
9     10 -> 11  0.996400
10    11 -> 12  0.993967
11    12 -> 13  0.994670
12    13 -> 14  0.999855
13    14 -> 15  0.996739
14    15 -> 16  1.000528
15    16 -> 17  1.003739
16    17 -> 18  0.993098

In [ ]:
incurred_cdf_table = calculate_cdfs(incurred_selected_ldfs)

incurred_cdf_table

   Development       LDF       CDF
0       1 -> 2  1.998324  3.194659
1       2 -> 3  1.290667  1.598669
2       3 -> 4  1.123524  1.238639
3       4 -> 5  1.072546  1.102459
4       5 -> 6  1.046308  1.027890
5       6 -> 7  1.018509  0.982397
6       7 -> 8  1.000398  0.964545
7       8 -> 9  0.989474  0.964161
8      9 -> 10  0.995176  0.974418
9     10 -> 11  0.996400  0.979141
10    11 -> 12  0.993967  0.982679
11    12 -> 13  0.994670  0.988644
12    13 -> 14  0.999855  0.993942
13    14 -> 15  0.996739  0.994086
14    15 -> 16  1.000528  0.997338
15    16 -> 17  1.003739  0.996812
16    17 -> 18  0.993098  0.993098

In [ ]:
incurred_cdf_lookup = {}

for i, cdf in enumerate(
    incurred_cdf_table["CDF"],
    start=1
):
    incurred_cdf_lookup[i] = cdf

incurred_cdf_lookup[len(incurred_cdf_table) + 1] = 1.0

In [ ]:
incurred_latest_diag = get_latest_diagonal(incurred_cum)
incurred_latest_diag.head()

   AccidentYear  DevelopmentAge  LatestValue
0          1978              18      25469.0
1          1979              17      19991.0
2          1980              16      32168.0
3          1981              15      40096.0
4          1982              14      40200.0

In [ ]:
ultimate_table_incurred = estimate_ultimate_losses(
    incurred_latest_diag,
    incurred_cdf_lookup
)
ultimate_table_incurred["ReservePct"] = (
    ultimate_table_incurred["Reserve"] /
    ultimate_table_incurred["Ultimate"]
)
ultimate_table_incurred

,AccidentYear,DevelopmentAge,LatestValue,CDF,Ultimate,Reserve,ReservePct
0,1978.0,18,25469.0,1.000000,25469.000000,0.000000,0.000000
1,1979.0,17,19991.0,0.993098,19853.028893,-137.971107,-0.006950
2,1980.0,16,32168.0,0.996812,32065.432631,-102.567369,-0.003199
3,1981.0,15,40096.0,0.997338,39989.273105,-106.726895,-0.002669
4,1982.0,14,40200.0,0.994086,39962.267475,-237.732525,-0.005949
5,1983.0,13,37075.0,0.993942,36850.392949,-224.607051,-0.006095
6,1984.0,12,51382.0,0.988644,50798.490462,-583.509538,-0.011487
7,1985.0,11,42378.0,0.982679,41643.990166,-734.009834,-0.017626
8,1986.0,10,44383.0,0.979141,43457.229804,-925.770196,-0.021303
9,1987.0,9,44196.0,0.974418,43065.395658,-1130.604342,-0.026253
10,1988.0,8,40398.0,0.964161,38950.185485,-1447.814515,-0.037171
11,1989.0,7,45501.0,0.964545,43887.755841,-1613.244159,-0.036758
12,1990.0,6,49300.0,0.982397,48432.183120,-867.816880,-0.017918
13,1991.0,5,41132.0,1.027890,42279.166683,1147.166683,0.027133
14,1992.0,4,44075.0,1.102459,48590.870334,4515.870334,0.092937
15,1993.0,3,34230.0,1.238639,42398.599057,8168.599057,0.192662
16,1994.0,2,23126.0,1.598669,36970.829976,13844.829976,0.374480
17,1995.0,1,9715.0,3.194659,31036.113598,21321.113598,0.686978

In [ ]:
comparison = pd.DataFrame({
    "PaidUltimate":
        ultimate_table_paid["Ultimate"],

    "IncurredUltimate":
        ultimate_table_incurred["Ultimate"]
})

comparison["Difference"] = (
    comparison["PaidUltimate"]
    - comparison["IncurredUltimate"]
)

comparison

    PaidUltimate  IncurredUltimate    Difference
0   25469.000000      25469.000000      0.000000
1   19847.130460      19853.028893     -5.898433
2   32059.594043      32065.432631     -5.838588
3   39257.384355      39989.273105   -731.888750
4   39910.496322      39962.267475    -51.771153
5   37080.626435      36850.392949    230.233486
6   49962.996697      50798.490462   -835.493765
7   41689.697210      41643.990166     45.707044
8   44248.394839      43457.229804    791.165035
9   44713.405456      43065.395658   1648.009798
10  39435.354613      38950.185485    485.169128
11  48152.408751      43887.755841   4264.652910
12  53646.306714      48432.183120   5214.123594
13  54335.359373      42279.166683  12056.192690
14  70850.335910      48590.870334  22259.465575
15  61885.866915      42398.599057  19487.267858
16  61472.824352      36970.829976  24501.994376
17  68006.363826      31036.113598  36970.250227

In [ ]:
# ==================================================
# RESERVE DIAGNOSTICS AGENT
# ==================================================

In [ ]:
diag = ultimate_table_paid.merge(
    ultimate_table_incurred,
    on="AccidentYear",
    suffixes=("_Paid", "_Incurred")
)

In [ ]:
diag["Difference"] = (
    diag["Ultimate_Paid"]
    - diag["Ultimate_Incurred"]
)

diag["Pct_Difference"] = (
    diag["Difference"]
    / diag["Ultimate_Incurred"]
)

In [ ]:
def divergence_flag(x):

    x = abs(x)

    if x > 0.25:
        return "FAIL"

    elif x > 0.10:
        return "WARNING"

    return "PASS"

In [ ]:
diag["DivergenceStatus"] = (
    diag["Pct_Difference"]
    .apply(divergence_flag)
)

In [ ]:
diag[
    [
        "AccidentYear",
        "Ultimate_Paid",
        "Ultimate_Incurred",
        "Difference",
        "Pct_Difference",
        "DivergenceStatus"
    ]
]

,AccidentYear,Ultimate_Paid,Ultimate_Incurred,Difference,Pct_Difference,DivergenceStatus
0,1978.0,25469.000000,25469.000000,0.000000,0.000000,PASS
1,1979.0,19847.130460,19853.028893,-5.898433,-0.000297,PASS
2,1980.0,32059.594043,32065.432631,-5.838588,-0.000182,PASS
3,1981.0,39257.384355,39989.273105,-731.888750,-0.018302,PASS
4,1982.0,39910.496322,39962.267475,-51.771153,-0.001296,PASS
5,1983.0,37080.626435,36850.392949,230.233486,0.006248,PASS
6,1984.0,49962.996697,50798.490462,-835.493765,-0.016447,PASS
7,1985.0,41689.697210,41643.990166,45.707044,0.001098,PASS
8,1986.0,44248.394839,43457.229804,791.165035,0.018206,PASS
9,1987.0,44713.405456,43065.395658,1648.009798,0.038268,PASS
10,1988.0,39435.354613,38950.185485,485.169128,0.012456,PASS
11,1989.0,48152.408751,43887.755841,4264.652910,0.097172,PASS
12,1990.0,53646.306714,48432.183120,5214.123594,0.107658,WARNING
13,1991.0,54335.359373,42279.166683,12056.192690,0.285157,FAIL
14,1992.0,70850.335910,48590.870334,22259.465575,0.458100,FAIL
15,1993.0,61885.866915,42398.599057,19487.267858,0.459621,FAIL
16,1994.0,61472.824352,36970.829976,24501.994376,0.662739,FAIL
17,1995.0,68006.363826,31036.113598,36970.250227,1.191201,FAIL

In [ ]:
diag["DivergenceStatus"].value_counts()

DivergenceStatus
PASS       12
FAIL        5
WARNING     1
Name: count, dtype: int64

In [ ]:
diag.loc[
    diag["DivergenceStatus"] != "PASS",
    [
        "AccidentYear",
        "Pct_Difference",
        "DivergenceStatus"
    ]
]

    AccidentYear  Pct_Difference DivergenceStatus
12        1990.0        0.107658          WARNING
13        1991.0        0.285157             FAIL
14        1992.0        0.458100             FAIL
15        1993.0        0.459621             FAIL
16        1994.0        0.662739             FAIL
17        1995.0        1.191201             FAIL

In [ ]:
diag = diag.merge(
    paid_latest_diag[
        ["AccidentYear", "DevelopmentAge"]
    ],
    on="AccidentYear",
    how="left"
)

In [ ]:
diag[
    ["AccidentYear", "DevelopmentAge"]
]

    AccidentYear  DevelopmentAge
0         1978.0              18
1         1979.0              17
2         1980.0              16
3         1981.0              15
4         1982.0              14
5         1983.0              13
6         1984.0              12
7         1985.0              11
8         1986.0              10
9         1987.0               9
10        1988.0               8
11        1989.0               7
12        1990.0               6
13        1991.0               5
14        1992.0               4
15        1993.0               3
16        1994.0               2
17        1995.0               1

In [ ]:
diag["CDF"] = (
    diag["DevelopmentAge"]
    .map(paid_cdf_lookup)
)

In [ ]:
diag[
    ["AccidentYear", "DevelopmentAge", "CDF"]
]

    AccidentYear  DevelopmentAge        CDF
0         1978.0              18   1.000000
1         1979.0              17   1.000511
2         1980.0              16   1.002082
3         1981.0              15   1.003563
4         1982.0              14   1.012212
5         1983.0              13   1.019988
6         1984.0              12   1.028871
7         1985.0              11   1.043312
8         1986.0              10   1.072558
9         1987.0               9   1.112108
10        1988.0               8   1.181973
11        1989.0               7   1.290292
12        1990.0               6   1.500806
13        1991.0               5   1.845066
14        1992.0               4   2.506646
15        1993.0               3   4.080835
16        1994.0               2   7.720777
17        1995.0               1  24.956464

In [ ]:
diag["RemainingDevelopment"] = (
    diag["CDF"] - 1
)

In [ ]:
def immature_flag(x):

    if x > 0.50:
        return "IMMATURE"

    return "MATURE"

In [ ]:
diag["ImmaturityStatus"] = (
    diag["RemainingDevelopment"]
    .apply(immature_flag)
)

In [ ]:
diag[
    [
        "AccidentYear",
        "DevelopmentAge",
        "CDF",
        "RemainingDevelopment",
        "ImmaturityStatus",
        "DivergenceStatus"
    ]
]

,AccidentYear,DevelopmentAge,CDF,RemainingDevelopment,ImmaturityStatus,DivergenceStatus
0,1978.0,18,1.000000,0.000000,MATURE,PASS
1,1979.0,17,1.000511,0.000511,MATURE,PASS
2,1980.0,16,1.002082,0.002082,MATURE,PASS
3,1981.0,15,1.003563,0.003563,MATURE,PASS
4,1982.0,14,1.012212,0.012212,MATURE,PASS
5,1983.0,13,1.019988,0.019988,MATURE,PASS
6,1984.0,12,1.028871,0.028871,MATURE,PASS
7,1985.0,11,1.043312,0.043312,MATURE,PASS
8,1986.0,10,1.072558,0.072558,MATURE,PASS
9,1987.0,9,1.112108,0.112108,MATURE,PASS
10,1988.0,8,1.181973,0.181973,MATURE,PASS
11,1989.0,7,1.290292,0.290292,MATURE,PASS
12,1990.0,6,1.500806,0.500806,IMMATURE,WARNING
13,1991.0,5,1.845066,0.845066,IMMATURE,FAIL
14,1992.0,4,2.506646,1.506646,IMMATURE,FAIL
15,1993.0,3,4.080835,3.080835,IMMATURE,FAIL
16,1994.0,2,7.720777,6.720777,IMMATURE,FAIL
17,1995.0,1,24.956464,23.956464,IMMATURE,FAIL

In [ ]:
from google.colab import userdata

API_KEY = userdata.get("GEMINI_API_KEY")

print(API_KEY[:10])   # quick test

AQ.Ab8RN6J

In [ ]:
!pip install -q google-genai

In [ ]:
from google import genai
from google.colab import userdata

client = genai.Client(
    api_key=userdata.get("GEMINI_API_KEY")
)

In [ ]:
response = client.models.generate_content(
    model="gemini-2.5-flash",
    contents="You are an actuary. Say hello."
)

print(response.text)

Hello there!

Always a pleasure to connect. How can I help you today?

In [ ]:
test_prompt = """
You are a reserving actuary.

Diagnostic Summary:

PASS: 12 accident years
WARNING: 1 accident year
FAIL: 5 accident years

Accident years 1991-1995 show significant divergence
between Paid and Incurred Chain Ladder estimates.

These same accident years are classified as immature.

Provide a brief actuarial interpretation.
"""

response = client.models.generate_content(
    model="gemini-2.5-flash",
    contents=test_prompt
)

print(response.text)

Here's a brief actuarial interpretation:

The majority of accident years (12 PASS) demonstrate stable development patterns, providing a solid foundation for traditional Chain Ladder methods. The 1 WARNING accident year warrants closer monitoring for any emerging adverse development or data anomalies.

However, the 5 FAIL accident years (1991-1995) present a significant concern. Despite their age, these years are classified as 'immature,' which is unusual and strongly suggests a very long-tailed line of business, potentially with latent liabilities, structured settlements, or claims with extremely protracted development.

The significant divergence between Paid and Incurred Chain Ladder estimates for these immature, long-tail years highlights the unreliability of these two methods when applied in isolation.

*   **Paid Chain Ladder** is likely premature and thus highly volatile/unreliable given the lack of sufficient payments for immature years.
*   **Incurred Chain Ladder**, while often more robust for immature periods, is also showing instability. This could indicate issues with case reserve adequacy, inconsistent case reserving practices, volatile claim reporting patterns, or the impact of large, late-developing claims that are skewing development factors.

**Key Interpretation:** For these critical long-tail years, standard Chain Ladder methods are failing to provide consistent or reliable ultimate loss estimates. The immaturity despite their age signifies a high degree of uncertainty about ultimate liabilities.

**Recommendations:**
1.  **Do not rely solely on Chain Ladder** for AYs 1991-1995. These years require deeper actuarial judgment and the application of alternative reserving methodologies, such as Bornhuetter-Ferguson, frequency-severity analysis, or a ground-up analysis of large claims and specific policy features.
2.  **Investigate the root cause** of the extended immaturity and divergence. This includes reviewing claims handling practices, policy characteristics (e.g., unlimited coverage, long statute of limitations), and data quality for these specific accident years.
3.  **Explicitly acknowledge the high degree of uncertainty** when presenting estimates for these accident years.